name 'aws-base'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures aws-base'
long_description 'Installs/Configures aws-base'
version '0.1.0'
